name: own_splitwise_copy
description: A starting point for Dart libraries or applications.
version: 1.0.0
uses-material-design: true
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

#  qr_code_scanner: ^1.1.0



  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  uuid: ^4.0.0
  graphview: ^1.2.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.3.1
  collection: ^1.17.1
  flutter_graph_view: ^1.2.0
#  flutter_barcode_scanner: ^2.0.0
#  permission_handler: ^11.1.0



  #  intl: ^0.20.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3


dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

